//! Bug reporter — creates GitHub issues from triaged error groups.
//!
//! Handles deduplication, formatting, rate limit checking, and issue creation.
//! All GitHub API calls go through this module — no GitHub-specific code elsewhere.

use crate::log_scanner::ErrorGroup;
use temm1e_core::types::error::Temm1eError;

const GITHUB_API: &str = "https://api.github.com";
const REPO: &str = "temm1e-labs/temm1e";
const USER_AGENT: &str = "TEMM1E-BugReporter";
/// Pin to a specific API version for long-term stability.
const API_VERSION: &str = "2022-11-28";
/// Max issue body length (GitHub limit is 65536, leave margin).
const MAX_ISSUE_BODY: usize = 60000;

/// Build standard GitHub API headers.
fn github_headers(token: &str) -> reqwest::header::HeaderMap {
    let mut headers = reqwest::header::HeaderMap::new();
    headers.insert(
        "Authorization",
        format!("Bearer {}", token).parse().unwrap(),
    );
    headers.insert("User-Agent", USER_AGENT.parse().unwrap());
    headers.insert("Accept", "application/vnd.github+json".parse().unwrap());
    headers.insert("X-GitHub-Api-Version", API_VERSION.parse().unwrap());
    headers
}

/// Check if an issue with this error signature already exists.
pub async fn is_duplicate(
    client: &reqwest::Client,
    token: &str,
    signature: &str,
) -> Result<bool, Temm1eError> {
    let sig_prefix: String = signature.chars().take(60).collect();
    let query = format!(
        "repo:{} is:open label:auto-reported \"{}\"",
        REPO, sig_prefix
    );
    let url = format!(
        "{}/search/issues?q={}",
        GITHUB_API,
        urlencoding::encode(&query)
    );

    let resp = client
        .get(&url)
        .headers(github_headers(token))
        .send()
        .await
        .map_err(|e| Temm1eError::Tool(format!("GitHub search failed: {}", e)))?;

    // Check rate limit before proceeding
    let remaining: u32 = resp
        .headers()
        .get("x-ratelimit-remaining")
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.parse().ok())
        .unwrap_or(100);

    if remaining < 10 {
        tracing::info!(
            remaining,
            "GitHub rate limit nearly exhausted, deferring bug report"
        );
        return Err(Temm1eError::Tool(
            "GitHub rate limit nearly exhausted".to_string(),
        ));
    }

    let body: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Temm1eError::Tool(format!("GitHub search parse error: {}", e)))?;

    let count = body
        .get("total_count")
        .and_then(|c| c.as_u64())
        .unwrap_or(0);
    Ok(count > 0)
}

/// Format an issue body from a triaged error group.
pub fn format_issue_body(
    error: &ErrorGroup,
    triage_explanation: &str,
    version: &str,
    os_info: &str,
) -> String {
    let body = format!(
        "## [BUG] {}\n\n\
         **Auto-reported by Tem {} on {}**\n\n\
         ### Error\n```\n{}\n```\n\n\
         ### Location\n`{}`\n\n\
         ### Context\n\
         - Version: {}\n\
         - OS: {}\n\
         - Occurrences: {} in last 6 hours\n\n\
         ### Triage\n{}\n\n\
         ---\n\
         *This issue was automatically generated by Tem's self-diagnosis system.*\n\
         *User reviewed and approved before submission.*",
        error.message,
        version,
        chrono::Utc::now().format("%Y-%m-%d"),
        error.message,
        error.location.as_deref().unwrap_or("unknown"),
        version,
        os_info,
        error.count,
        triage_explanation,
    );

    // Truncate if too long (safe UTF-8 boundary)
    if body.len() > MAX_ISSUE_BODY {
        let safe_end = body
            .char_indices()
            .take_while(|(index, _)| *index <= MAX_ISSUE_BODY)
            .last()
            .map(|(i, _)| i)
            .unwrap_or(0);
        format!(
            "{}\n\n[Report truncated — exceeded size limit]",
            &body[..safe_end]
        )
    } else {
        body
    }
}

/// Create a GitHub issue. Returns the issue URL.
pub async fn create_issue(
    client: &reqwest::Client,
    token: &str,
    title: &str,
    body: &str,
) -> Result<String, Temm1eError> {
    let url = format!("{}/repos/{}/issues", GITHUB_API, REPO);

    let payload = serde_json::json!({
        "title": title,
        "body": body,
        "labels": ["bug", "auto-reported"]
    });

    let resp = client
        .post(&url)
        .headers(github_headers(token))
        .json(&payload)
        .send()
        .await
        .map_err(|e| Temm1eError::Tool(format!("GitHub issue creation failed: {}", e)))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let text = resp.text().await.unwrap_or_default();
        return Err(Temm1eError::Tool(format!(
            "GitHub issue creation failed ({}): {}",
            status, text
        )));
    }

    let body: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| Temm1eError::Tool(format!("GitHub response parse error: {}", e)))?;

    let url = body
        .get("html_url")
        .and_then(|u| u.as_str())
        .unwrap_or("unknown")
        .to_string();

    Ok(url)
}

/// Check PAT scopes and return dangerous ones (if any).
pub async fn check_pat_scopes(
    client: &reqwest::Client,
    token: &str,
) -> Result<(String, Vec<String>), Temm1eError> {
    let resp = client
        .get(format!("{}/user", GITHUB_API))
        .headers(github_headers(token))
        .send()
        .await
        .map_err(|e| Temm1eError::Tool(format!("GitHub PAT validation failed: {}", e)))?;

    if !resp.status().is_success() {
        return Err(Temm1eError::Tool(format!(
            "GitHub PAT validation failed: {}",
            resp.status()
        )));
    }

    let scopes = resp
        .headers()
        .get("x-oauth-scopes")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("")
        .to_string();

    let dangerous: Vec<String> = scopes
        .split(',')
        .map(|s| s.trim().to_string())
        .filter(|s| {
            matches!(
                s.as_str(),
                "repo"
                    | "admin:org"
                    | "delete_repo"
                    | "admin:repo_hook"
                    | "write:packages"
                    | "admin:gpg_key"
                    | "admin:ssh_signing_key"
            )
        })
        .collect();

    Ok((scopes, dangerous))
}

/// LLM triage categories for bug classification.
pub const TRIAGE_CATEGORIES: &[(&str, &str)] = &[
    (
        "BUG",
        "A defect in TEMM1E code — panic, logic error, unhandled case, assertion failure",
    ),
    (
        "USER_ERROR",
        "User misconfiguration, invalid input, wrong command usage",
    ),
    (
        "TRANSIENT",
        "Temporary issue — network timeout, API rate limit, provider 500 error, DNS failure",
    ),
    (
        "CONFIG",
        "Missing or invalid configuration, missing environment variable, wrong file permissions",
    ),
];

/// Build the triage prompt for an error group.
pub fn build_triage_prompt(error: &ErrorGroup) -> String {
    let categories: String = TRIAGE_CATEGORIES
        .iter()
        .map(|(name, desc)| format!("- {}: {}", name, desc))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "Classify this error into exactly one category:\n{}\n\n\
         Error: {}\nLocation: {}\nOccurrences: {} in last 6 hours\n\n\
         Respond with ONLY the category name and one sentence explanation.",
        categories,
        error.message,
        error.location.as_deref().unwrap_or("unknown"),
        error.count,
    )
}

/// Parse the LLM triage response into a category.
pub fn parse_triage_category(response: &str) -> &'static str {
    let text = response.trim();
    if text.starts_with("BUG") {
        "BUG"
    } else if text.starts_with("USER_ERROR") {
        "USER_ERROR"
    } else if text.starts_with("TRANSIENT") {
        "TRANSIENT"
    } else if text.starts_with("CONFIG") {
        "CONFIG"
    } else {
        "UNKNOWN"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_triage_bug() {
        assert_eq!(parse_triage_category("BUG: panic in context.rs"), "BUG");
    }

    #[test]
    fn parse_triage_transient() {
        assert_eq!(
            parse_triage_category("TRANSIENT: network timeout"),
            "TRANSIENT"
        );
    }

    #[test]
    fn parse_triage_unknown() {
        assert_eq!(parse_triage_category("gibberish response"), "UNKNOWN");
    }

    #[test]
    fn format_body_truncates() {
        let long_msg = "x".repeat(70000);
        let error = ErrorGroup {
            signature: "test".to_string(),
            message: long_msg,
            location: None,
            count: 1,
            timestamps: vec![],
            sample_lines: vec![],
        };
        let body = format_issue_body(&error, "BUG", "4.1.2", "Darwin");
        assert!(body.len() <= MAX_ISSUE_BODY + 100); // margin for truncation notice
        assert!(body.contains("[Report truncated"));
    }

    #[test]
    fn unicode_report_truncation_preserves_boundaries() {
        for offset in 0..4 {
            let error = ErrorGroup {
                signature: "test".into(),
                message: "x".into(),
                location: None,
                count: 1,
                timestamps: vec![],
                sample_lines: vec![],
            };
            let triage = format!("{}{}", "a".repeat(offset), "界".repeat(22000));
            let body = format_issue_body(&error, &triage, "test", "test");
            assert!(body.contains("[Report truncated"));
            assert!(body.len() <= MAX_ISSUE_BODY + 100);
        }
    }

    #[test]
    fn build_triage_prompt_includes_all_categories() {
        let error = ErrorGroup {
            signature: "test".to_string(),
            message: "panic: test".to_string(),
            location: Some("src/main.rs:42".to_string()),
            count: 3,
            timestamps: vec![],
            sample_lines: vec![],
        };
        let prompt = build_triage_prompt(&error);
        assert!(prompt.contains("BUG"));
        assert!(prompt.contains("USER_ERROR"));
        assert!(prompt.contains("TRANSIENT"));
        assert!(prompt.contains("CONFIG"));
        assert!(prompt.contains("panic: test"));
    }
}
