//! `temm1e search install` — one-click SearXNG install via Docker/Podman.
//!
//! Detects docker or podman on PATH, writes a baked settings.yml with
//! formats: [html, json] enabled, runs the container, verifies it's up,
//! and persists the URL to the user's temm1e config.
//!
//! No new deps — uses tokio::process, std::fs, reqwest (already in tree).

use std::io::{self, Write};
use std::path::{Path, PathBuf};
use tokio::process::Command;
use tokio::time::{timeout, Duration};

const CONTAINER_NAME: &str = "temm1e-searxng";
const HOST_PORT: u16 = 8888;
const CONTAINER_PORT: u16 = 8080;
const IMAGE: &str = "searxng/searxng";

/// Baked SearXNG settings.yml — enables JSON output + sensible default engines.
const BAKED_SETTINGS_YML: &str = r#"# TEMM1E SearXNG settings — generated by `temm1e search install`
# Safe to customize; re-running the installer will NOT overwrite this file.
use_default_settings: true

server:
  secret_key: "temm1e-local-do-not-expose"
  limiter: false
  image_proxy: false
  port: 8080
  bind_address: "0.0.0.0"

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

ui:
  default_theme: simple
"#;

pub async fn run_install() -> anyhow::Result<()> {
    print_header();

    // Step 1: detect docker/podman
    let runtime = match detect_container_runtime() {
        Some(r) => {
            println!("  ✓ Found container runtime: {r}");
            r
        }
        None => {
            eprintln!("  ✗ Neither `docker` nor `podman` found on PATH.");
            eprintln!();
            eprintln!("  Tem needs a container runtime to install SearXNG locally.");
            eprintln!("  Install options:");
            eprintln!("    - Docker Desktop (Windows/macOS): https://www.docker.com/products/docker-desktop/");
            eprintln!(
                "    - Docker Engine (Linux):          https://docs.docker.com/engine/install/"
            );
            eprintln!("    - Podman (all platforms):         https://podman.io/docs/installation");
            eprintln!();
            eprintln!("  You can still use web_search with all the free backends — just not unlimited general web.");
            return Ok(());
        }
    };

    // Step 2: verify runtime is accessible (daemon running?)
    if !verify_runtime(&runtime).await {
        eprintln!("  ✗ `{runtime}` is installed but not responding.");
        eprintln!("    On Docker Desktop: launch the app from Applications/Start menu.");
        eprintln!("    On Linux:          `sudo systemctl start docker`");
        return Ok(());
    }

    // Step 3: check for existing container
    if container_exists(&runtime, CONTAINER_NAME).await {
        println!("  ℹ A container named '{CONTAINER_NAME}' already exists.");
        print!("  Remove and recreate? [y/N]: ");
        io::stdout().flush().ok();
        let mut input = String::new();
        io::stdin().read_line(&mut input).ok();
        if !matches!(input.trim().to_lowercase().as_str(), "y" | "yes") {
            println!("  ℹ Keeping existing container. Verifying and persisting URL...");
            let url = format!("http://localhost:{HOST_PORT}");
            persist_config(&url)?;
            verify_endpoint(&url).await;
            return Ok(());
        }
        remove_container(&runtime, CONTAINER_NAME).await;
    }

    // Step 4: prepare settings.yml
    let config_dir = settings_dir()?;
    let settings_path = config_dir.join("settings.yml");
    if !settings_path.exists() {
        std::fs::create_dir_all(&config_dir)?;
        std::fs::write(&settings_path, BAKED_SETTINGS_YML)?;
        println!("  ✓ Wrote settings.yml to {}", settings_path.display());
    } else {
        println!(
            "  ℹ Existing settings.yml found at {} — keeping user version",
            settings_path.display()
        );
    }

    // Step 5: confirm with user
    println!();
    println!("  About to run:");
    println!("    {runtime} run -d --name {CONTAINER_NAME} -p {HOST_PORT}:{CONTAINER_PORT} \\");
    println!("      -v {}:/etc/searxng {IMAGE}", config_dir.display());
    println!();
    print!("  Proceed? [Y/n]: ");
    io::stdout().flush().ok();
    let mut input = String::new();
    io::stdin().read_line(&mut input).ok();
    let trimmed = input.trim().to_lowercase();
    if matches!(trimmed.as_str(), "n" | "no") {
        println!("  ℹ Cancelled. No changes made.");
        return Ok(());
    }

    // Step 6: run the container
    println!("  ⧗ Pulling image and starting container (first run ~200 MB)...");
    let run_result = Command::new(&runtime)
        .arg("run")
        .arg("-d")
        .arg("--name")
        .arg(CONTAINER_NAME)
        .arg("-p")
        .arg(format!("{HOST_PORT}:{CONTAINER_PORT}"))
        .arg("-v")
        .arg(format!("{}:/etc/searxng", config_dir.display()))
        .arg("--restart=unless-stopped")
        .arg(IMAGE)
        .output()
        .await;

    match run_result {
        Ok(output) if output.status.success() => {
            println!("  ✓ Container started.");
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            eprintln!("  ✗ Container failed to start:");
            eprintln!("    {}", stderr.trim());
            return Ok(());
        }
        Err(e) => {
            eprintln!("  ✗ Failed to invoke {runtime}: {e}");
            return Ok(());
        }
    }

    // Step 7: verify endpoint (wait up to 30s for SearXNG to boot)
    let url = format!("http://localhost:{HOST_PORT}");
    println!("  ⧗ Waiting for SearXNG to respond at {url}...");
    let verified = verify_endpoint_with_retries(&url, 30).await;
    if !verified {
        eprintln!("  ⚠ Could not verify SearXNG at {url} within 30s. It may still be booting.");
        eprintln!("    Check with: {runtime} logs {CONTAINER_NAME}");
    }

    // Step 8: persist URL to config
    match persist_config(&url) {
        Ok(path) => {
            println!("  ✓ Persisted searxng_url to {}", path.display());
        }
        Err(e) => {
            eprintln!("  ⚠ Could not persist config: {e}");
            eprintln!("    You can set it manually: `export TEMM1E_SEARXNG_URL={url}`");
        }
    }

    println!();
    println!("  Done. The agent now has `searxng` available as a search backend.");
    println!("  To stop:   {runtime} stop {CONTAINER_NAME}");
    println!("  To remove: {runtime} rm -f {CONTAINER_NAME}");
    Ok(())
}

fn print_header() {
    println!();
    println!("  ╭───────────────────────────────────────────╮");
    println!("  │   TEMM1E — Install Local SearXNG          │");
    println!("  ╰───────────────────────────────────────────╯");
    println!();
    println!("  This will install SearXNG in a local container.");
    println!("  SearXNG is an open-source metasearch engine that aggregates");
    println!("  Google, Bing, DuckDuckGo, and 70+ other sources. Running it");
    println!("  locally gives Tem unlimited general web search with zero cost.");
    println!();
}

/// Detect `docker` or `podman` on PATH using a manual walk.
/// Returns the binary name to invoke.
fn detect_container_runtime() -> Option<String> {
    for candidate in ["docker", "podman"] {
        if which_on_path(candidate).is_some() {
            return Some(candidate.to_string());
        }
    }
    None
}

/// Manual `which` that walks PATH. Returns the first full path found.
fn which_on_path(binary: &str) -> Option<PathBuf> {
    let path_env = std::env::var_os("PATH")?;
    let separator = if cfg!(windows) { ';' } else { ':' };
    let exts: &[&str] = if cfg!(windows) {
        &[".exe", ".cmd", ".bat", ""]
    } else {
        &[""]
    };
    for dir in path_env.to_string_lossy().split(separator) {
        if dir.is_empty() {
            continue;
        }
        for ext in exts {
            let candidate = Path::new(dir).join(format!("{binary}{ext}"));
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

/// Verify the container runtime is accessible (daemon running).
async fn verify_runtime(runtime: &str) -> bool {
    match timeout(
        Duration::from_secs(5),
        Command::new(runtime).arg("info").output(),
    )
    .await
    {
        Ok(Ok(output)) => output.status.success(),
        _ => false,
    }
}

/// Check whether a container with `name` already exists (any state).
async fn container_exists(runtime: &str, name: &str) -> bool {
    let output = Command::new(runtime)
        .arg("ps")
        .arg("-a")
        .arg("--format")
        .arg("{{.Names}}")
        .output()
        .await;
    match output {
        Ok(out) if out.status.success() => {
            let stdout = String::from_utf8_lossy(&out.stdout);
            stdout.lines().any(|line| line.trim() == name)
        }
        _ => false,
    }
}

async fn remove_container(runtime: &str, name: &str) {
    let _ = Command::new(runtime)
        .arg("rm")
        .arg("-f")
        .arg(name)
        .output()
        .await;
}

/// Canonical settings directory.
fn settings_dir() -> anyhow::Result<PathBuf> {
    Some(temm1e_core::config::data_dir().join("searxng"))
        .ok_or_else(|| anyhow::anyhow!("could not determine home directory"))
}

/// Verify the SearXNG endpoint responds with a valid JSON search response.
async fn verify_endpoint(url: &str) -> bool {
    let full = format!("{url}/search?q=test&format=json");
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(5))
        .build()
        .unwrap_or_else(|_| reqwest::Client::new());
    match client.get(&full).send().await {
        Ok(r) => r.status().is_success(),
        Err(_) => false,
    }
}

/// Poll the endpoint up to N seconds, 1-second intervals.
async fn verify_endpoint_with_retries(url: &str, max_secs: u64) -> bool {
    for _ in 0..max_secs {
        if verify_endpoint(url).await {
            return true;
        }
        tokio::time::sleep(Duration::from_secs(1)).await;
    }
    false
}

/// Persist the searxng_url to the user's temm1e config file.
/// Read-modify-write pattern: load existing TOML, merge in the setting,
/// write back. Preserves existing keys.
fn persist_config(url: &str) -> anyhow::Result<PathBuf> {
    let config_path = Some(temm1e_core::config::data_dir().join("temm1e.toml"))
        .ok_or_else(|| anyhow::anyhow!("could not determine home directory"))?;

    // Ensure parent exists
    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Load existing content if present
    let existing = std::fs::read_to_string(&config_path).unwrap_or_default();

    // Very simple merge: if [tools.web_search] section is missing, append it.
    // If it exists but doesn't have searxng_url, append the key.
    // If it exists with searxng_url, replace the value.
    let merged = merge_searxng_url(&existing, url);
    std::fs::write(&config_path, merged)?;
    Ok(config_path)
}

/// Merge `searxng_url = "<url>"` into the `[tools.web_search]` section of a TOML string.
/// Preserves existing keys. Creates the section if missing.
fn merge_searxng_url(existing: &str, url: &str) -> String {
    let target_line = format!("searxng_url = \"{url}\"");

    // If the key already exists anywhere, replace its value line.
    if existing.contains("searxng_url") {
        let mut out = String::new();
        for line in existing.lines() {
            if line.trim_start().starts_with("searxng_url") {
                out.push_str(&target_line);
            } else {
                out.push_str(line);
            }
            out.push('\n');
        }
        return out;
    }

    // If the section exists, append the key inside it (simple: after the header).
    if let Some(idx) = existing.find("[tools.web_search]") {
        let (before, after) = existing.split_at(idx);
        // Find end of the section header line
        let header_end = after.find('\n').map(|n| n + 1).unwrap_or(after.len());
        let (header, rest) = after.split_at(header_end);
        let mut out = String::new();
        out.push_str(before);
        out.push_str(header);
        out.push_str(&target_line);
        out.push('\n');
        out.push_str(rest);
        return out;
    }

    // Section missing — append it at the end
    let mut out = existing.to_string();
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out.push_str("[tools.web_search]\n");
    out.push_str(&target_line);
    out.push('\n');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn which_on_path_finds_nothing_for_nonexistent() {
        assert!(which_on_path("this-binary-should-not-exist-xxxxx").is_none());
    }

    #[test]
    fn merge_searxng_url_into_empty_toml() {
        let merged = merge_searxng_url("", "http://localhost:8888");
        assert!(merged.contains("[tools.web_search]"));
        assert!(merged.contains("searxng_url = \"http://localhost:8888\""));
    }

    #[test]
    fn merge_searxng_url_preserves_existing_keys() {
        let existing = "[tools]\nshell = true\n\n[gateway]\nport = 8080\n";
        let merged = merge_searxng_url(existing, "http://localhost:8888");
        assert!(merged.contains("shell = true"));
        assert!(merged.contains("port = 8080"));
        assert!(merged.contains("[tools.web_search]"));
        assert!(merged.contains("searxng_url ="));
    }

    #[test]
    fn merge_searxng_url_replaces_existing_value() {
        let existing = "[tools.web_search]\nsearxng_url = \"http://old:8888\"\nmax_results = 20\n";
        let merged = merge_searxng_url(existing, "http://new:8888");
        assert!(merged.contains("http://new:8888"));
        assert!(!merged.contains("http://old:8888"));
        assert!(merged.contains("max_results = 20"));
    }

    #[test]
    fn merge_searxng_url_adds_to_existing_section() {
        let existing = "[tools.web_search]\nmax_results = 20\n";
        let merged = merge_searxng_url(existing, "http://localhost:8888");
        assert!(merged.contains("[tools.web_search]"));
        assert!(merged.contains("max_results = 20"));
        assert!(merged.contains("searxng_url"));
    }

    #[test]
    fn merge_searxng_url_appends_trailing_newline() {
        let merged = merge_searxng_url("[gateway]\nport = 8080", "http://localhost:8888");
        assert!(merged.ends_with('\n'));
    }
}
